package route

import (
	"net/http"

	"github.com/evergreen-ci/evergreen"
	"github.com/evergreen-ci/evergreen/cloud"
	"github.com/evergreen-ci/evergreen/model"
	"github.com/evergreen-ci/evergreen/rest/data"
	"github.com/evergreen-ci/gimlet"
	"github.com/evergreen-ci/gimlet/acl"
	"github.com/gorilla/handlers"
	"github.com/mongodb/amboy"
)

const defaultLimit = 100

type HandlerOpts struct {
	APIQueue            amboy.Queue
	TaskDispatcher      model.TaskQueueItemDispatcher
	TaskAliasDispatcher model.TaskQueueItemDispatcher
	GithubSecret        []byte
}

// AttachHandler attaches the api's request handlers to the given mux router.
// It builds a Connector then attaches each of the main functions for
// the api to the router.
func AttachHandler(app *gimlet.APIApp, opts HandlerOpts) {
	sc := &data.DBConnector{}
	env := evergreen.GetEnvironment()
	settings := env.Settings()
	parsleyURL := settings.Ui.ParsleyUrl

	// Middleware
	requireUser := gimlet.NewRequireAuthHandler()
	requireUserOrTask := NewUserOrTaskAuthMiddleware()
	requireUserOrTaskAuthOnly := NewUserOrTaskAuthOnlyMiddleware()
	requireValidGithubPayload := NewGithubAuthMiddleware()
	requireValidSNSPayload := NewSNSAuthMiddleware()
	requireTask := NewTaskAuthMiddleware()
	requireHost := NewHostAuthMiddleware()
	addProject := NewProjectContextMiddleware()
	requireProjectAdmin := NewProjectAdminMiddleware()
	requireAlertmanager := NewAlertmanagerMiddleware()
	requireBackstage := newBackstageMiddleware()
	createProject := NewCanCreateMiddleware()
	rateLimit := NewRateLimitMiddleware(env, evergreen.RateLimitSurfaceREST)
	adminSettings := RequiresSuperUserPermission(evergreen.PermissionAdminSettings, evergreen.AdminSettingsEdit)
	sendNotifications := NewSendNotificationMiddleware()
	createDistro := RequiresSuperUserPermission(evergreen.PermissionDistroCreate, evergreen.DistroCreate)
	editRoles := RequiresSuperUserPermission(evergreen.PermissionRoleModify, evergreen.RoleModify)
	viewTasks := RequiresProjectPermission(evergreen.PermissionTasks, evergreen.TasksView)
	editTasks := RequiresProjectPermission(evergreen.PermissionTasks, evergreen.TasksBasic)
	editAnnotations := RequiresProjectPermission(evergreen.PermissionAnnotations, evergreen.AnnotationsModify)
	viewAnnotations := RequiresProjectPermission(evergreen.PermissionAnnotations, evergreen.AnnotationsView)
	submitPatches := RequiresProjectPermission(evergreen.PermissionPatches, evergreen.PatchSubmit)
	viewProjectSettings := RequiresProjectPermission(evergreen.PermissionProjectSettings, evergreen.ProjectSettingsView)
	editProjectSettings := RequiresProjectPermission(evergreen.PermissionProjectSettings, evergreen.ProjectSettingsEdit)
	viewDistroSettings := RequiresDistroPermission(evergreen.PermissionDistroSettings, evergreen.DistroSettingsView)
	editDistroSettings := RequiresDistroPermission(evergreen.PermissionDistroSettings, evergreen.DistroSettingsEdit)
	removeDistroSettings := RequiresDistroPermission(evergreen.PermissionDistroSettings, evergreen.DistroSettingsAdmin)
	compress := gimlet.WrapperHandlerMiddleware(handlers.CompressHandler)

	app.AddWrapper(NewRequestHostMiddleware())
	app.AddWrapper(gimlet.WrapperMiddleware(allowCORS))

	// Clients
	stsManager := cloud.GetSTSManager(false)

	// Agent protocol routes
	app.AddRoute("/agent/perf_monitoring_url").Version(2).Get().Wrap(requireHost).RouteHandler(makeGetPerfURL(settings.PerfMonitoringURL))
	app.AddRoute("/agent/setup").Version(2).Get().Wrap(requireHost).RouteHandler(makeAgentSetup(settings))
	app.AddRoute("/distros/{distro_id}/ami").Version(2).Get().Wrap(requireTask).RouteHandler(makeGetDistroAMI())
	app.AddRoute("/distros/{distro_id}/client_urls").Version(2).Get().Wrap(requireHost).RouteHandler(makeGetDistroClientURLs(env))
	app.AddRoute("/hosts/{host_id}/agent/next_task").Version(2).Get().Wrap(requireHost).RouteHandler(makeHostAgentNextTask(env, opts.TaskDispatcher, opts.TaskAliasDispatcher))
	app.AddRoute("/hosts/{host_id}/task/{task_id}/end").Version(2).Post().Wrap(requireHost, requireTask).RouteHandler(makeHostAgentEndTask(env))
	app.AddRoute("/hosts/{host_id}/disable").Version(2).Post().Wrap(requireHost).RouteHandler(makeDisableHostHandler(env))
	app.AddRoute("/hosts/{host_id}/is_up").Version(2).Post().Wrap(requireHost).RouteHandler(makeHostIsUpPostHandler(env))
	app.AddRoute("/hosts/{host_id}/provisioning_options").Version(2).Get().Wrap(requireHost).RouteHandler(makeHostProvisioningOptionsGetHandler(env))
	app.AddRoute("/hosts/{task_id}/create").Version(2).Post().Wrap(requireTask).RouteHandler(makeHostCreateRouteManager(env))
	app.AddRoute("/hosts/{task_id}/list").Version(2).Get().Wrap(requireTask).RouteHandler(makeHostListRouteManager())
	app.AddRoute("/task/{task_id}/").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeFetchTask())
	app.AddRoute("/task/{task_id}/display_task").Version(2).Get().Wrap(requireTask).RouteHandler(makeGetDisplayTaskHandler())
	app.AddRoute("/task/{task_id}/distro_view").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeGetDistroView())
	app.AddRoute("/task/{task_id}/host_view").Version(2).Get().Wrap(requireTask, requireHost).RouteHandler(makeGetHostView())
	app.AddRoute("/task/{task_id}/downstreamParams").Version(2).Post().Wrap(requireTask).RouteHandler(makeSetDownstreamParams())
	app.AddRoute("/task/{task_id}/expansions_and_vars").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeGetExpansionsAndVars(settings))
	app.AddRoute("/task/{task_id}/files").Version(2).Post().Wrap(requireTask, requireHost).RouteHandler(makeAttachFiles())
	app.AddRoute("/task/{task_id}/generate").Version(2).Post().Wrap(requireTask).RouteHandler(makeGenerateTasksHandler(env))
	app.AddRoute("/task/{task_id}/generate").Version(2).Get().Wrap(requireTask).RouteHandler(makeGenerateTasksPollHandler())
	app.AddRoute("/task/{task_id}/new_push").Version(2).Post().Wrap(requireTask).RouteHandler(makeNewPush())
	app.AddRoute("/task/{task_id}/heartbeat").Version(2).Post().Wrap(requireTask, requireHost).RouteHandler(makeHeartbeat())
	app.AddRoute("/task/{task_id}/parser_project").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeGetParserProject(env))
	app.AddRoute("/task/{task_id}/project_ref").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeGetProjectRef())
	app.AddRoute("/task/{task_id}/high_exec_timeout").Version(2).Post().Wrap(requireTask).RouteHandler(makeReportHighExecTimeout())
	app.AddRoute("/task/{task_id}/s3_usage").Version(2).Post().Wrap(requireTask).RouteHandler(makeReportS3Usage())
	app.AddRoute("/task/{task_id}/set_results_info").Version(2).Post().Wrap(requireTask).RouteHandler(makeSetTaskResultsInfoHandler())
	app.AddRoute("/task/{task_id}/start").Version(2).Post().Wrap(requireTask, requireHost).RouteHandler(makeStartTask(env))
	app.AddRoute("/task/{task_id}/test_logs").Version(2).Post().Wrap(requireTask, requireHost).RouteHandler(makeAttachTestLog(settings))
	app.AddRoute("/task/{task_id}/test_results").Version(2).Post().Wrap(requireTask, requireHost).RouteHandler(makeAttachTestResults(env))
	app.AddRoute("/task/{task_id}/patch").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeServePatch())
	app.AddRoute("/task/{task_id}/version").Version(2).Get().Wrap(requireTask).RouteHandler(makeServeVersion())
	app.AddRoute("/task/{task_id}/git/patchfile/{patchfile_id}").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeGitServePatchFile())
	app.AddRoute("/task/{task_id}/github_dynamic_access_token").Version(2).Delete().Wrap(requireUserOrTask).RouteHandler(makeRevokeGitHubDynamicAccessToken(env))
	app.AddRoute("/task/{task_id}/installation_token/{owner}/{repo}").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeCreateInstallationToken(env))
	app.AddRoute("/task/{task_id}/github_dynamic_access_token/{owner}/{repo}").Version(2).Post().Wrap(requireUserOrTask).RouteHandler(makeCreateGitHubDynamicAccessToken(env))
	app.AddRoute("/task/{task_id}/keyval/inc").Version(2).Post().Wrap(requireTask).RouteHandler(makeKeyvalPluginInc())
	app.AddRoute("/task/{task_id}/manifest/load").Version(2).Get().Wrap(requireUserOrTask).RouteHandler(makeManifestLoad(settings))
	app.AddRoute("/task/{task_id}/update_push_status").Version(2).Post().Wrap(requireTask).RouteHandler(makeUpdatePushStatus())
	app.AddRoute("/task/{task_id}/restart").Version(2).Post().Wrap(requireTask).RouteHandler(makeMarkTaskForRestart())
	app.AddRoute("/task/{task_id}/check_run").Version(2).Post().Wrap(requireTask).RouteHandler(makeCheckRun(settings))
	app.AddRoute("/task/{task_id}/aws/assume_role").Version(2).Post().Wrap(requireUserOrTask).RouteHandler(makeAWSAssumeRole(stsManager))
	app.AddRoute("/task/{task_id}/mark_git_ref_not_found").Version(2).Patch().Wrap(requireTask).RouteHandler(makeMarkMergeQueueGitRefNotFound())

	// REST v2 API Routes
	app.AddRoute("/").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makePlaceHolder())
	app.AddRoute("/admin/banner").Version(2).Get().Wrap(requireUser).RouteHandler(makeFetchAdminBanner())
	app.AddRoute("/admin/banner").Version(2).Post().Wrap(requireUser, adminSettings).RouteHandler(makeSetAdminBanner())
	app.AddRoute("/admin/uiv2_url").Version(2).Get().Wrap(requireUser).RouteHandler(makeFetchAdminUIV2Url())
	app.AddRoute("/admin/events").Version(2).Get().Wrap(requireUser, adminSettings).RouteHandler(makeFetchAdminEvents())
	app.AddRoute("/admin/spawn_hosts").Version(2).Get().Wrap(requireUser, adminSettings).RouteHandler(makeFetchSpawnHostUsage())
	app.AddRoute("/admin/restart/tasks").Version(2).Post().Wrap(adminSettings).RouteHandler(makeRestartRoute(opts.APIQueue))
	app.AddRoute("/admin/revert").Version(2).Post().Wrap(requireUser, adminSettings).RouteHandler(makeRevertRouteManager())
	app.AddRoute("/admin/service_flags").Version(2).Get().Wrap(requireUser).RouteHandler(makeFetchServiceFlags())
	app.AddRoute("/admin/service_flags").Version(2).Post().Wrap(requireUser, adminSettings).RouteHandler(makeSetServiceFlagsRouteManager())
	app.AddRoute("/admin/settings").Version(2).Get().Wrap(requireUser, adminSettings).RouteHandler(makeFetchAdminSettings())
	app.AddRoute("/admin/settings").Version(2).Post().Wrap(requireUser, adminSettings).RouteHandler(makeSetAdminSettings())
	app.AddRoute("/admin/task_limits").Version(2).Get().Wrap(requireUser).RouteHandler(makeFetchTaskLimits())
	app.AddRoute("/admin/task_queue").Version(2).Delete().Wrap(requireUser, adminSettings).RouteHandler(makeClearTaskQueueHandler())
	app.AddRoute("/admin/service_users").Version(2).Get().Wrap(requireUser, adminSettings).RouteHandler(makeGetServiceUsers())
	app.AddRoute("/admin/service_users").Version(2).Post().Wrap(requireUser, adminSettings).RouteHandler(makeUpdateServiceUser())
	app.AddRoute("/admin/service_users").Version(2).Delete().Wrap(requireUser, adminSettings).RouteHandler(makeDeleteServiceUser())
	app.AddRoute("/alias/{project_id}").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchAliases())
	app.AddRoute("/auth").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(&authPermissionGetHandler{})
	app.AddRoute("/auth/token_exchange/authorize").Version(2).Get().Wrap(requireUser, rateLimit).Handler(tokenExchangeAuthorizeHandler(env))
	app.AddRoute("/auth/token_exchange/callback").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeTokenExchangeCallback(env))
	app.AddRoute("/builds/{build_id}").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetBuildByID(env))
	app.AddRoute("/builds/{build_id}").Version(2).Patch().Wrap(requireUser, editTasks, rateLimit).RouteHandler(makeChangeStatusForBuild())
	app.AddRoute("/builds/{build_id}/abort").Version(2).Post().Wrap(requireUser, editTasks, rateLimit).RouteHandler(makeAbortBuild())
	app.AddRoute("/builds/{build_id}/restart").Version(2).Post().Wrap(requireUser, editTasks, rateLimit).RouteHandler(makeRestartBuild())
	app.AddRoute("/builds/{build_id}/tasks").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeFetchTasksByBuild(parsleyURL))
	app.AddRoute("/builds/{build_id}/annotations").Version(2).Get().Wrap(requireUser, viewAnnotations, rateLimit).RouteHandler(makeFetchAnnotationsByBuild())
	// degraded_mode is used by Kanopy's alertmanager instance, which is only able to perform basic auth for REST, so it does not pass in user info
	app.AddRoute("/degraded_mode").Version(2).Post().Wrap(requireAlertmanager, rateLimit).RouteHandler(makeSetDegradedMode())
	// Do not apply viewDistroSettings middleware, as it requires a specific distro ID.
	app.AddRoute("/distros").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeDistroRoute())
	app.AddRoute("/distros/{distro_id}").Version(2).Get().Wrap(requireUser, viewDistroSettings, rateLimit).RouteHandler(makeGetDistroByID())
	app.AddRoute("/distros/{distro_id}").Version(2).Patch().Wrap(requireUser, editDistroSettings, rateLimit).RouteHandler(makePatchDistroByID())
	app.AddRoute("/distros/{distro_id}").Version(2).Delete().Wrap(requireUser, removeDistroSettings, rateLimit).RouteHandler(makeDeleteDistroByID())
	app.AddRoute("/distros/{distro_id}").Version(2).Put().Wrap(requireUser, createDistro, rateLimit).RouteHandler(makePutDistro())
	app.AddRoute("/distros/{distro_id}/setup").Version(2).Get().Wrap(requireUser, editDistroSettings, rateLimit).RouteHandler(makeGetDistroSetup())
	app.AddRoute("/distros/{distro_id}/setup").Version(2).Patch().Wrap(requireUser, editDistroSettings, rateLimit).RouteHandler(makeChangeDistroSetup())
	app.AddRoute("/distros/{distro_id}/copy/{new_distro_id}").Version(2).Put().Wrap(requireUser, editDistroSettings, rateLimit).RouteHandler(makeCopyDistro())

	app.AddRoute("/hooks/github").Version(2).Post().Wrap(requireValidGithubPayload, rateLimit).RouteHandler(makeGithubHooksRoute(sc, opts.APIQueue, opts.GithubSecret, settings))
	app.AddRoute("/hooks/aws").Version(2).Post().Wrap(requireValidSNSPayload, rateLimit).RouteHandler(makeEC2SNS(env, opts.APIQueue))

	app.AddRoute("/host/filter").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchHostFilter())
	app.AddRoute("/host/start_processes").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeHostStartProcesses(env))
	app.AddRoute("/host/get_processes").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeHostGetProcesses(env))
	app.AddRoute("/hosts").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchHosts())
	app.AddRoute("/hosts").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeSpawnHostCreateRoute(env))
	app.AddRoute("/hosts").Version(2).Patch().Wrap(requireUser, rateLimit).RouteHandler(makeChangeHostsStatuses(env))
	app.AddRoute("/hosts/{host_id}").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetHostByID())
	app.AddRoute("/hosts/{host_id}").Version(2).Patch().Wrap(requireUser, rateLimit).RouteHandler(makeHostModifyRouteManager(env))
	app.AddRoute("/hosts/{host_id}/stop").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeHostStopManager(env))
	app.AddRoute("/hosts/{host_id}/start").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeHostStartManager(env))
	app.AddRoute("/hosts/{host_id}/change_password").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeHostChangePassword(env))
	app.AddRoute("/hosts/{host_id}/extend_expiration").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeExtendHostExpiration())
	app.AddRoute("/hosts/{host_id}/terminate").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeTerminateHostRoute())
	app.AddRoute("/hosts/{host_id}/attach").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeAttachVolume(env))
	app.AddRoute("/hosts/{host_id}/detach").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeDetachVolume(env))
	app.AddRoute("/hosts/ip_address/{ip_address}").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetHostByIpAddress())
	app.AddRoute("/volumes").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetVolumes())
	app.AddRoute("/volumes").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeCreateVolume(env))
	app.AddRoute("/volumes/{volume_id}").Version(2).Wrap(requireUser, rateLimit).Delete().RouteHandler(makeDeleteVolume(env))
	app.AddRoute("/volumes/{volume_id}").Version(2).Wrap(requireUser, rateLimit).Patch().RouteHandler(makeModifyVolume(env))
	app.AddRoute("/volumes/{volume_id}").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetVolumeByID())
	app.AddRoute("/keys").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchKeys())
	app.AddRoute("/keys").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeSetKey())
	app.AddRoute("/keys/{key_name}").Version(2).Delete().Wrap(requireUser, rateLimit).RouteHandler(makeDeleteKeys())
	app.AddRoute("/notifications/slack").Version(2).Post().Wrap(requireUser, sendNotifications, rateLimit).RouteHandler(makeSlackNotification(env))
	app.AddRoute("/notifications/email").Version(2).Post().Wrap(requireUser, sendNotifications, rateLimit).RouteHandler(makeEmailNotification(env))
	app.AddRoute("/panic").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makePanicReport())
	app.AddRoute("/patches/{patch_id}").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeFetchPatchByID())
	app.AddRoute("/patches/{patch_id}").Version(2).Patch().Wrap(requireUser, submitPatches, rateLimit).RouteHandler(makeChangePatchStatus(env))
	app.AddRoute("/patches/{patch_id}/abort").Version(2).Post().Wrap(requireUser, submitPatches, rateLimit).RouteHandler(makeAbortPatch())
	app.AddRoute("/patches/{patch_id}/configure").Version(2).Post().Wrap(requireUser, submitPatches, rateLimit).RouteHandler(makeSchedulePatchHandler(env))
	app.AddRoute("/patches/{patch_id}/raw").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makePatchRawHandler())
	app.AddRoute("/patches/{patch_id}/raw_modules").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeModuleRawHandler())
	app.AddRoute("/patches/{patch_id}/restart").Version(2).Post().Wrap(requireUser, submitPatches, rateLimit).RouteHandler(makeRestartPatch())
	app.AddRoute("/patches/{patch_id}/estimated_generated_tasks").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeCountEstimatedGeneratedTasks())
	app.AddRoute("/projects").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchProjectsRoute())
	app.AddRoute("/projects/test_alias").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetProjectAliasResultsHandler())
	app.AddRoute("/projects/{project_id}").Version(2).Delete().Wrap(requireUser, addProject, requireProjectAdmin, editProjectSettings, rateLimit).RouteHandler(makeDeleteProject())
	app.AddRoute("/projects/{project_id}").Version(2).Get().Wrap(requireUser, addProject, viewProjectSettings, rateLimit).RouteHandler(makeGetProjectByID())
	app.AddRoute("/projects/{project_id}").Version(2).Patch().Wrap(requireUser, addProject, requireProjectAdmin, editProjectSettings, rateLimit).RouteHandler(makePatchProjectByID(settings))
	app.AddRoute("/projects/{project_id}/repotracker").Version(2).Post().Wrap(requireUser, addProject, editTasks, rateLimit).RouteHandler(makeRunRepotrackerForProject())
	app.AddRoute("/projects/{project_id}").Version(2).Put().Wrap(requireUser, createProject, rateLimit).RouteHandler(makePutProjectByID(env))
	app.AddRoute("/projects/{project_id}/copy").Version(2).Post().Wrap(requireUser, addProject, requireProjectAdmin, editProjectSettings, rateLimit).RouteHandler(makeCopyProject(env))
	app.AddRoute("/projects/{project_id}/copy/variables").Version(2).Post().Wrap(requireUser, addProject, requireProjectAdmin, editProjectSettings, rateLimit).RouteHandler(makeCopyVariables())
	app.AddRoute("/projects/{project_id}/backstage_variables").Version(2).Post().Wrap(requireUser, requireBackstage, rateLimit).RouteHandler(makeBackstageVariablesPost())
	app.AddRoute("/projects/{project_id}/events").Version(2).Get().Wrap(requireUser, addProject, requireProjectAdmin, viewProjectSettings, rateLimit).RouteHandler(makeFetchProjectEvents())
	app.AddRoute("/projects/{project_id}/patches").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makePatchesByProjectRoute())
	app.AddRoute("/projects/{project_id}/recent_versions").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeFetchProjectVersionsLegacy())
	app.AddRoute("/projects/{project_id}/revisions/{commit_hash}/tasks").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeTasksByProjectAndCommitHandler(parsleyURL))
	app.AddRoute("/projects/{project_id}/task_reliability").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetProjectTaskReliability())
	app.AddRoute("/projects/{project_id}/task_stats").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetProjectTaskStats())
	app.AddRoute("/projects/{project_id}/versions").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetProjectVersionsHandler())
	app.AddRoute("/projects/{project_id}/versions").Version(2).Patch().Wrap(requireUser, requireProjectAdmin, rateLimit).RouteHandler(makeModifyProjectVersionsHandler())
	app.AddRoute("/projects/{project_id}/tasks/{task_name}").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetProjectTasksHandler())
	app.AddRoute("/projects/{project_id}/task_executions").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetProjectTaskExecutionsHandler())
	app.AddRoute("/projects/{project_id}/patch_trigger_aliases").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeFetchPatchTriggerAliases())
	app.AddRoute("/projects/{project_id}/parameters").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeFetchParameters())
	app.AddRoute("/projects/{project_id}/variants/{variant_name}/quarantine").Version(2).Post().Wrap(requireUser, addProject, editTasks, rateLimit).RouteHandler(makeVariantQuarantineHandler())
	app.AddRoute("/projects/{project_id}/variants/{variant_name}/unquarantine").Version(2).Post().Wrap(requireUser, addProject, editTasks, rateLimit).RouteHandler(makeVariantUnquarantineHandler())
	app.AddRoute("/projects/{project_id}/variants/{variant_name}/quarantine_status").Version(2).Get().Wrap(requireUser, addProject, viewTasks, rateLimit).RouteHandler(makeVariantQuarantineStatusHandler())
	app.AddRoute("/permissions").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(&permissionsGetHandler{})
	app.AddRoute("/permissions/users").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetAllUsersPermissions(env.RoleManager()))
	app.AddRoute("/roles").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(acl.NewGetAllRolesHandler(env.RoleManager()))
	app.AddRoute("/roles/{role_id}/users").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetUsersWithRole())
	app.AddRoute("/select/tests").Version(2).Post().Wrap(requireUserOrTaskAuthOnly, rateLimit).RouteHandler(makeSelectTestsHandler(env))
	app.AddRoute("/status/cli_version").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchCLIVersionRoute(env))
	app.AddRoute("/status/hosts/distros").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeHostStatusByDistroRoute())
	app.AddRoute("/status/notifications").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchNotifcationStatusRoute())
	app.AddRoute("/status/recent_tasks").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeRecentTaskStatusHandler())
	app.AddRoute("/subscriptions").Version(2).Delete().Wrap(requireUser, rateLimit).RouteHandler(makeDeleteSubscription())
	app.AddRoute("/subscriptions").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchSubscription())
	app.AddRoute("/subscriptions").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeSetSubscription())
	app.AddRoute("/tasks/{task_id}").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetTaskRoute(parsleyURL))
	app.AddRoute("/tasks/{task_id}").Version(2).Patch().Wrap(requireUser, addProject, editTasks, rateLimit).RouteHandler(makeModifyTaskRoute())
	app.AddRoute("/tasks/{task_id}/artifacts/url").Version(2).Patch().Wrap(requireUser, addProject, requireProjectAdmin, editTasks, rateLimit).RouteHandler(makeUpdateArtifactURLRoute())
	app.AddRoute("/tasks/{task_id}/annotations").Version(2).Get().Wrap(requireUser, viewAnnotations, rateLimit).RouteHandler(makeFetchAnnotationsByTask())
	app.AddRoute("/tasks/{task_id}/annotation").Version(2).Put().Wrap(requireUser, editAnnotations, rateLimit).RouteHandler(makePutAnnotationsByTask())
	app.AddRoute("/tasks/{task_id}/annotation").Version(2).Patch().Wrap(requireUser, editAnnotations, rateLimit).RouteHandler(makePatchAnnotationsByTask())
	app.AddRoute("/tasks/{task_id}/created_ticket").Version(2).Put().Wrap(requireUser, editAnnotations, rateLimit).RouteHandler(makeCreatedTicketByTask())
	app.AddRoute("/tasks/{task_id}/abort").Version(2).Post().Wrap(requireUser, editTasks, rateLimit).RouteHandler(makeTaskAbortHandler())
	app.AddRoute("/tasks/{task_id}/manifest").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetManifestHandler())
	app.AddRoute("/tasks/{task_id}/quarantine").Version(2).Post().Wrap(requireUser, addProject, editTasks, rateLimit).RouteHandler(makeTaskQuarantineHandler())
	app.AddRoute("/tasks/{task_id}/unquarantine").Version(2).Post().Wrap(requireUser, addProject, editTasks, rateLimit).RouteHandler(makeTaskUnquarantineHandler())
	app.AddRoute("/tasks/{task_id}/restart").Version(2).Post().Wrap(requireUser, addProject, editTasks, rateLimit).RouteHandler(makeTaskRestartHandler())
	app.AddRoute("/tasks/{task_id}/tests").Version(2).Get().Wrap(requireUser, addProject, viewTasks, rateLimit).RouteHandler(makeFetchTestsForTask(env, sc))
	app.AddRoute("/tasks/{task_id}/tests/count").Version(2).Get().Wrap(requireUser, addProject, viewTasks, rateLimit).RouteHandler(makeFetchTestCountForTask())
	app.AddRoute("/tasks/{task_id}/generated_tasks").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetGeneratedTasks())
	app.AddRoute("/tasks/{task_id}/build/TaskLogs").Version(2).Get().Wrap(requireUser, viewTasks, compress, rateLimit).RouteHandler(makeGetTaskLogs())
	app.AddRoute("/tasks/{task_id}/build/TestLogs/{path}").Version(2).Get().Wrap(requireUser, viewTasks, compress, rateLimit).RouteHandler(makeGetTestLogs())
	app.AddRoute("/tasks/{task_id}/github_dynamic_access_tokens").Version(2).Delete().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeDeleteGitHubDynamicAccessTokens())
	app.AddRoute("/user/settings").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchUserConfig())
	app.AddRoute("/user/settings").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeSetUserConfig())
	app.AddRoute("/users/{user_id}").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetUserHandler())
	app.AddRoute("/users/{user_id}/hosts").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeFetchHosts())
	app.AddRoute("/users/{user_id}/patches").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeUserPatchHandler())
	app.AddRoute("/users/offboard_user").Version(2).Post().Wrap(requireUser, editRoles, rateLimit).RouteHandler(makeOffboardUser(env))
	app.AddRoute("/users/rename_user").Version(2).Post().Wrap(requireUser, editRoles, rateLimit).RouteHandler(makeRenameUser(env))
	app.AddRoute("/users/{user_id}/permissions").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetUserPermissions(env.RoleManager()))
	app.AddRoute("/users/{user_id}/permissions").Version(2).Post().Wrap(requireUser, editRoles, rateLimit).RouteHandler(makeModifyUserPermissions(env.RoleManager()))
	app.AddRoute("/users/{user_id}/permissions").Version(2).Delete().Wrap(requireUser, editRoles, rateLimit).RouteHandler(makeDeleteUserPermissions(env.RoleManager()))
	app.AddRoute("/users/{user_id}/permission-details").Version(2).Get().Wrap(requireUser, rateLimit).RouteHandler(makeGetUserPermissionDetails(env.RoleManager()))
	app.AddRoute("/users/{user_id}/roles").Version(2).Post().Wrap(requireUser, editRoles, rateLimit).RouteHandler(makeModifyUserRoles(env.RoleManager()))
	app.AddRoute("/validate").Version(2).Post().Wrap(requireUser, rateLimit).RouteHandler(makeValidateProject())
	app.AddRoute("/versions/{version_id}").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetVersionByID())
	app.AddRoute("/versions/{version_id}").Version(2).Patch().Wrap(requireUser, editTasks, rateLimit).RouteHandler(makePatchVersion())
	app.AddRoute("/versions/{version_id}/abort").Version(2).Post().Wrap(requireUser, editTasks, rateLimit).RouteHandler(makeAbortVersion())
	app.AddRoute("/versions/{version_id}/activate_tasks").Version(2).Post().Wrap(requireUser, editTasks, rateLimit).RouteHandler(makeActivateVersionTasks())
	app.AddRoute("/versions/{version_id}/builds").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetVersionBuilds(env))
	app.AddRoute("/versions/{version_id}/restart").Version(2).Post().Wrap(requireUser, editTasks, rateLimit).RouteHandler(makeRestartVersion())
	app.AddRoute("/versions/{version_id}/annotations").Version(2).Get().Wrap(requireUser, viewAnnotations, rateLimit).RouteHandler(makeFetchAnnotationsByVersion())
	app.AddRoute("/versions/{version_id}/manifest").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetVersionManifest())

	// Diagnostic manifest proof routes compare project and module revision movement across system versions.
	app.AddRoute("/versions/{version_id}/manifest/proof").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetVersionManifestProof())
	app.AddRoute("/versions/{version_id}/manifest/proof/history").Version(2).Get().Wrap(requireUser, viewTasks, rateLimit).RouteHandler(makeGetVersionManifestProofHistory())

	// Add an options method to every GET, POST request to handle pre-flight Options requests.
	// These requests must not check for credentials and just validate whether a route exists
	// And allows requests from a origin.
	for _, route := range app.Routes() {
		if route.HasMethod(http.MethodPost) || route.HasMethod(http.MethodGet) {
			app.AddRoute(route.GetRoute()).Version(2).Options().RouteHandler(makeOptionsHandler())
		}
	}
}
