package command

import (
	"context"
	"net/http"
	"os"
	"path"
	"path/filepath"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/evergreen-ci/evergreen"
	"github.com/evergreen-ci/evergreen/agent/internal"
	"github.com/evergreen-ci/evergreen/agent/internal/client"
	"github.com/evergreen-ci/evergreen/util"
	"github.com/evergreen-ci/pail"
	"github.com/evergreen-ci/utility"
	"github.com/mitchellh/mapstructure"
	"github.com/mongodb/grip"
	"github.com/pkg/errors"
)

// cacheRestore is a command that downloads and extracts a previously saved
// cache artifact from S3, setting a cache-hit expansion the rest of the task
// can branch on.
type cacheRestore struct {
	// CacheName identifies the cache. It drives the local tarball filename and
	// the cache-hit expansion name.
	CacheName string `mapstructure:"name" plugin:"expand"`

	// Bucket is the S3 bucket holding the cache.
	Bucket string `mapstructure:"bucket" plugin:"expand"`

	// RemotePath is the S3 key prefix under which caches are stored.
	RemotePath string `mapstructure:"remote_path" plugin:"expand"`

	// KeyFiles are file paths whose contents are folded into the cache key.
	KeyFiles []string `mapstructure:"key_files" plugin:"expand"`

	// KeyExpansions are string values folded into the cache key. At least one
	// is required so every cache makes an explicit invalidation choice.
	KeyExpansions []string `mapstructure:"key_expansions" plugin:"expand"`

	// AwsKey, AwsSecret, and AwsSessionToken are the user's credentials for
	// authenticating interactions with S3.
	AwsKey          string `mapstructure:"aws_key" plugin:"expand"`
	AwsSecret       string `mapstructure:"aws_secret" plugin:"expand"`
	AwsSessionToken string `mapstructure:"aws_session_token" plugin:"expand"`

	// RoleARN is an ARN that should be assumed to make the S3 request.
	RoleARN string `mapstructure:"role_arn" plugin:"expand"`

	// Region is the S3 region where the bucket is located. It defaults to
	// "us-east-1".
	Region string `mapstructure:"region" plugin:"region"`

	// assumedRoleARN is set when the command is using temporary credentials
	// that were generated by an ec2.assume_role command.
	assumedRoleARN string

	// existingCredentials holds passed-in temporary credentials and their
	// expiration, populated by an ec2.assume_role command.
	existingCredentials *aws.Credentials

	bucket   pail.Bucket
	taskData client.TaskData
	base
}

func cacheRestoreFactory() Command   { return &cacheRestore{} }
func (c *cacheRestore) Name() string { return "cache.restore" }

func (c *cacheRestore) ParseParams(params map[string]any) error {
	decoder, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		WeaklyTypedInput: true,
		Result:           c,
	})
	if err != nil {
		return errors.Wrap(err, "initializing mapstructure decoder")
	}
	if err := decoder.Decode(params); err != nil {
		return errors.Wrap(err, "decoding mapstructure params")
	}

	return errors.Wrap(c.validate(), "validating params")
}

func (c *cacheRestore) validate() error {
	catcher := grip.NewSimpleCatcher()

	catcher.Add(validateCacheName(c.CacheName))
	catcher.Wrapf(validateS3BucketName(c.Bucket), "validating bucket name '%s'", c.Bucket)
	catcher.NewWhen(c.RemotePath == "", "remote_path cannot be blank")
	catcher.NewWhen(len(c.KeyExpansions) == 0, "at least one key_expansions value is required")
	validateCacheCredentials(catcher, c.RoleARN, c.AwsKey, c.AwsSecret, c.AwsSessionToken)

	return catcher.Resolve()
}

func (c *cacheRestore) expandParams(conf *internal.TaskConfig) error {
	if err := util.ExpandValues(c, &conf.Expansions); err != nil {
		return errors.Wrap(err, "applying expansions")
	}
	if c.Region == "" {
		c.Region = evergreen.DefaultEC2Region
	}
	return nil
}

func (c *cacheRestore) Execute(ctx context.Context, comm client.Communicator, logger client.LoggerProducer, conf *internal.TaskConfig) error {
	c.taskData = client.TaskData{ID: conf.Task.Id, Secret: conf.Task.Secret}

	if err := c.expandParams(conf); err != nil {
		return errors.Wrap(err, "expanding params")
	}
	if err := c.validate(); err != nil {
		return errors.Wrap(err, "validating expanded params")
	}

	if expiration, found := getAssumedRoleExpiration(conf, c.AwsSessionToken); found {
		if info := getAssumedRoleInfo(conf, c.AwsSessionToken); info != nil {
			c.assumedRoleARN = info.RoleARN
		}
		c.existingCredentials = &aws.Credentials{
			AccessKeyID:     c.AwsKey,
			SecretAccessKey: c.AwsSecret,
			SessionToken:    c.AwsSessionToken,
			Expires:         expiration,
			CanExpire:       true,
		}
	}

	keyFiles := make([]string, len(c.KeyFiles))
	for i, keyFile := range c.KeyFiles {
		keyFiles[i] = GetWorkingDirectory(conf, keyFile)
	}
	key, err := computeCacheKey(keyFiles, c.KeyExpansions)
	if err != nil {
		return errors.Wrap(err, "computing cache key")
	}

	remoteKey := path.Join(c.RemotePath, key, c.CacheName+".tgz")
	localPath := filepath.Join(conf.WorkDir, c.CacheName+".tgz")
	hitExpansion := cacheHitExpansionName(c.CacheName)

	logger.Task().Infof(ctx, "cache.restore: computed cache key '%s'.", key)
	logger.Task().Infof(ctx, "cache.restore: looking up cache at '%s/%s'.", c.Bucket, remoteKey)

	httpClient := utility.GetHTTPClient()
	httpClient.Timeout = s3HTTPClientTimeout
	defer utility.PutHTTPClient(httpClient)
	if err := c.createPailBucket(ctx, comm, httpClient); err != nil {
		return errors.Wrap(err, "connecting to S3")
	}
	if err := c.bucket.Check(ctx); err != nil {
		return errors.Wrap(err, "checking bucket")
	}

	exists, err := c.bucket.Exists(ctx, remoteKey)
	if err != nil {
		return errors.Wrap(err, "checking for cache object")
	}
	if !exists {
		logger.Task().Infof(ctx, "cache.restore: cache miss for key '%s'.", key)
		conf.Expansions.Put(hitExpansion, "")
		return nil
	}

	if err := c.bucket.Download(ctx, remoteKey, localPath); err != nil {
		return errors.Wrapf(err, "downloading cache object '%s'", remoteKey)
	}

	// A 0-byte file is treated as a miss. This mirrors Evergreen's optional
	// s3.get behavior when the object is absent (DEVPROD-17632).
	info, err := os.Stat(localPath)
	if err != nil {
		return errors.Wrapf(err, "stating downloaded cache file '%s'", localPath)
	}
	if info.Size() == 0 {
		logger.Task().Infof(ctx, "cache.restore: cache miss (0-byte object) for key '%s'.", key)
		conf.Expansions.Put(hitExpansion, "")
		return nil
	}

	if err := c.extract(ctx, localPath, conf.WorkDir); err != nil {
		return errors.Wrap(err, "extracting cache archive")
	}

	logger.Task().Infof(ctx, "cache.restore: cache hit for key '%s', extracted into '%s'.", key, conf.WorkDir)
	conf.Expansions.Put(hitExpansion, "true")
	return nil
}

func (c *cacheRestore) extract(ctx context.Context, archivePath, dest string) error {
	f, err := os.Open(archivePath)
	if err != nil {
		return errors.Wrapf(err, "opening cache archive '%s'", archivePath)
	}
	defer f.Close()

	return errors.Wrap(extractTarball(ctx, f, dest, []string{}), "extracting tarball")
}

func (c *cacheRestore) createPailBucket(ctx context.Context, comm client.Communicator, httpClient *http.Client) error {
	opts := pail.S3Options{
		Region: c.Region,
		Name:   c.Bucket,
	}
	if c.getRoleARN() != "" {
		opts.Credentials = createEvergreenCredentials(comm, c.taskData, c.existingCredentials, c.getRoleARN(), nil)
	} else if c.AwsKey != "" {
		opts.Credentials = pail.CreateAWSStaticCredentials(c.AwsKey, c.AwsSecret, c.AwsSessionToken)
	}

	bucket, err := pail.NewS3MultiPartBucketWithHTTPClient(ctx, httpClient, opts)
	c.bucket = bucket
	return err
}

func (c *cacheRestore) getRoleARN() string {
	if c.assumedRoleARN != "" {
		return c.assumedRoleARN
	}
	return c.RoleARN
}
