package command

import (
	"context"
	"net/http"
	"os"
	"path"
	"path/filepath"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/smithy-go"
	"github.com/evergreen-ci/evergreen"
	"github.com/evergreen-ci/evergreen/agent/internal"
	"github.com/evergreen-ci/evergreen/agent/internal/client"
	"github.com/evergreen-ci/evergreen/util"
	"github.com/evergreen-ci/pail"
	"github.com/evergreen-ci/utility"
	"github.com/mitchellh/mapstructure"
	"github.com/mongodb/grip"
	"github.com/pkg/errors"
)

// cacheSave is a command that bundles paths into a tarball and uploads it to S3
// so a later task can restore them via cache.restore. It no-ops when the
// corresponding cache.restore already reported a hit.
type cacheSave struct {
	// CacheName identifies the cache. It drives the local tarball filename and
	// the cache-hit expansion name.
	CacheName string `mapstructure:"name" plugin:"expand"`

	// Bucket is the S3 bucket holding the cache.
	Bucket string `mapstructure:"bucket" plugin:"expand"`

	// RemotePath is the S3 key prefix under which caches are stored.
	RemotePath string `mapstructure:"remote_path" plugin:"expand"`

	// KeyFiles are file paths whose contents are folded into the cache key.
	KeyFiles []string `mapstructure:"key_files" plugin:"expand"`

	// KeyExpansions are string values folded into the cache key. At least one
	// is required so every cache makes an explicit invalidation choice.
	KeyExpansions []string `mapstructure:"key_expansions" plugin:"expand"`

	// Paths are file or directory paths, relative to the working directory, to
	// bundle into the tarball.
	Paths []string `mapstructure:"paths" plugin:"expand"`

	// AwsKey, AwsSecret, and AwsSessionToken are the user's credentials for
	// authenticating interactions with S3.
	AwsKey          string `mapstructure:"aws_key" plugin:"expand"`
	AwsSecret       string `mapstructure:"aws_secret" plugin:"expand"`
	AwsSessionToken string `mapstructure:"aws_session_token" plugin:"expand"`

	// RoleARN is an ARN that should be assumed to make the S3 request.
	RoleARN string `mapstructure:"role_arn" plugin:"expand"`

	// Region is the S3 region where the bucket is located. It defaults to
	// "us-east-1".
	Region string `mapstructure:"region" plugin:"region"`

	// assumedRoleARN is set when the command is using temporary credentials
	// that were generated by an ec2.assume_role command.
	assumedRoleARN string

	// existingCredentials holds passed-in temporary credentials and their
	// expiration, populated by an ec2.assume_role command.
	existingCredentials *aws.Credentials

	bucket   pail.Bucket
	taskData client.TaskData
	base
}

func cacheSaveFactory() Command   { return &cacheSave{} }
func (c *cacheSave) Name() string { return "cache.save" }

func (c *cacheSave) ParseParams(params map[string]any) error {
	decoder, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		WeaklyTypedInput: true,
		Result:           c,
	})
	if err != nil {
		return errors.Wrap(err, "initializing mapstructure decoder")
	}
	if err := decoder.Decode(params); err != nil {
		return errors.Wrap(err, "decoding mapstructure params")
	}

	return errors.Wrap(c.validate(), "validating params")
}

func (c *cacheSave) validate() error {
	catcher := grip.NewSimpleCatcher()

	catcher.Add(validateCacheName(c.CacheName))
	catcher.Wrapf(validateS3BucketName(c.Bucket), "validating bucket name '%s'", c.Bucket)
	catcher.NewWhen(c.RemotePath == "", "remote_path cannot be blank")
	catcher.NewWhen(len(c.KeyExpansions) == 0, "at least one key_expansions value is required")
	catcher.NewWhen(len(c.Paths) == 0, "at least one paths value is required")
	validateCacheCredentials(catcher, c.RoleARN, c.AwsKey, c.AwsSecret, c.AwsSessionToken)

	return catcher.Resolve()
}

func (c *cacheSave) expandParams(conf *internal.TaskConfig) error {
	if err := util.ExpandValues(c, &conf.Expansions); err != nil {
		return errors.Wrap(err, "applying expansions")
	}
	if c.Region == "" {
		c.Region = evergreen.DefaultEC2Region
	}
	return nil
}

func (c *cacheSave) Execute(ctx context.Context, comm client.Communicator, logger client.LoggerProducer, conf *internal.TaskConfig) error {
	c.taskData = client.TaskData{ID: conf.Task.Id, Secret: conf.Task.Secret}

	if err := c.expandParams(conf); err != nil {
		return errors.Wrap(err, "expanding params")
	}
	if err := c.validate(); err != nil {
		return errors.Wrap(err, "validating expanded params")
	}

	// The cache key is recomputed rather than read from an expansion that
	// cache.restore would have set, so the two commands aren't coupled through
	// hidden state. The hit expansion is only used to decide whether to skip.
	hitExpansion := cacheHitExpansionName(c.CacheName)
	if conf.Expansions.Get(hitExpansion) == "true" {
		logger.Task().Infof(ctx, "cache.save: skipping save because cache '%s' was already a hit on restore.", c.CacheName)
		return nil
	}

	if expiration, found := getAssumedRoleExpiration(conf, c.AwsSessionToken); found {
		if info := getAssumedRoleInfo(conf, c.AwsSessionToken); info != nil {
			c.assumedRoleARN = info.RoleARN
		}
		c.existingCredentials = &aws.Credentials{
			AccessKeyID:     c.AwsKey,
			SecretAccessKey: c.AwsSecret,
			SessionToken:    c.AwsSessionToken,
			Expires:         expiration,
			CanExpire:       true,
		}
	}

	keyFiles := make([]string, len(c.KeyFiles))
	for i, keyFile := range c.KeyFiles {
		keyFiles[i] = GetWorkingDirectory(conf, keyFile)
	}
	key, err := computeCacheKey(keyFiles, c.KeyExpansions)
	if err != nil {
		return errors.Wrap(err, "computing cache key")
	}

	remoteKey := path.Join(c.RemotePath, key, c.CacheName+".tgz")
	localPath := filepath.Join(conf.WorkDir, c.CacheName+".tgz")

	logger.Task().Infof(ctx, "cache.save: computed cache key '%s'.", key)
	logger.Task().Infof(ctx, "cache.save: bundling paths %s into '%s'.", c.Paths, localPath)

	if err := makeCacheArchive(ctx, conf.WorkDir, c.Paths, localPath, logger.Task()); err != nil {
		return errors.Wrap(err, "creating cache archive")
	}
	defer func() {
		logger.Task().Error(ctx, errors.Wrapf(os.Remove(localPath), "removing local cache archive '%s'", localPath))
	}()

	httpClient := utility.GetHTTPClient()
	httpClient.Timeout = s3HTTPClientTimeout
	defer utility.PutHTTPClient(httpClient)
	if err := c.createPailBucket(ctx, comm, httpClient); err != nil {
		return errors.Wrap(err, "connecting to S3")
	}
	if err := c.bucket.Check(ctx); err != nil {
		return errors.Wrap(err, "checking bucket")
	}

	if err := c.bucket.Upload(ctx, remoteKey, localPath); err != nil {
		// Skip-existing semantics: S3 reports PreconditionFailed when the
		// object already exists and IfNotExists is set on the request. That is
		// not an error for caching, it just means another task saved first.
		var apiErr smithy.APIError
		if errors.As(err, &apiErr) && apiErr.ErrorCode() == "PreconditionFailed" {
			logger.Task().Infof(ctx, "cache.save: not uploading because '%s/%s' already exists.", c.Bucket, remoteKey)
			return nil
		}
		return errors.Wrapf(err, "uploading cache object '%s'", remoteKey)
	}

	logger.Task().Infof(ctx, "cache.save: uploaded cache to '%s/%s'.", c.Bucket, remoteKey)
	return nil
}

func (c *cacheSave) createPailBucket(ctx context.Context, comm client.Communicator, httpClient *http.Client) error {
	opts := pail.S3Options{
		Region: c.Region,
		Name:   c.Bucket,
		// Skip-existing: never overwrite a cache that another task already saved.
		IfNotExists: true,
	}
	if c.getRoleARN() != "" {
		opts.Credentials = createEvergreenCredentials(comm, c.taskData, c.existingCredentials, c.getRoleARN(), nil)
	} else if c.AwsKey != "" {
		opts.Credentials = pail.CreateAWSStaticCredentials(c.AwsKey, c.AwsSecret, c.AwsSessionToken)
	}

	bucket, err := pail.NewS3MultiPartBucketWithHTTPClient(ctx, httpClient, opts)
	c.bucket = bucket
	return err
}

func (c *cacheSave) getRoleARN() string {
	if c.assumedRoleARN != "" {
		return c.assumedRoleARN
	}
	return c.RoleARN
}
