package command

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/smithy-go"
	"github.com/evergreen-ci/evergreen"
	"github.com/evergreen-ci/evergreen/agent/internal"
	"github.com/evergreen-ci/evergreen/agent/internal/client"
	"github.com/evergreen-ci/evergreen/util"
	"github.com/evergreen-ci/pail"
	"github.com/evergreen-ci/utility"
	"github.com/mitchellh/mapstructure"
	"github.com/mongodb/grip"
	"github.com/pkg/errors"
)

// cacheArchiveSuffix is the extension given to every cache tarball, both locally
// and as the final segment of its S3 key.
const cacheArchiveSuffix = ".tgz"

// cacheHitValue is the expansion value cache.restore sets on a hit and cache.save
// checks before deciding to skip.
const cacheHitValue = "true"

// cacheNameRegex constrains a cache name to characters that are safe in both an
// S3 object key and the derived cache-hit expansion name.
var cacheNameRegex = regexp.MustCompile(`^[a-zA-Z0-9-]+$`)

// cacheCommon holds the parameters and runtime state shared by cache.restore and
// cache.save. Both commands embed it. The embed must be tagged
// mapstructure:",squash" so these fields decode from top-level params, and
// plugin:"expand" so util.ExpandValues descends into the struct (it only
// recurses into struct fields that are themselves tagged expandable).
type cacheCommon struct {
	// CacheName identifies the cache. It drives the local tarball filename and
	// the cache-hit expansion name.
	CacheName string `mapstructure:"name" plugin:"expand"`

	// Bucket is the S3 bucket holding the cache.
	Bucket string `mapstructure:"bucket" plugin:"expand"`

	// RemotePath is the S3 key prefix under which caches are stored.
	RemotePath string `mapstructure:"remote_path" plugin:"expand"`

	// KeyFiles are file paths whose contents are folded into the cache key.
	KeyFiles []string `mapstructure:"key_files" plugin:"expand"`

	// KeyExpansions are string values folded into the cache key. At least one
	// is required so every cache makes an explicit invalidation choice.
	KeyExpansions []string `mapstructure:"key_expansions" plugin:"expand"`

	// PreserveSymlinks, when true, archives symlinks as symlinks (preserving
	// their targets) instead of dereferencing them into regular files. It is
	// folded into the cache key so symlink-aware caches never reuse older
	// dereferenced ones, and so it must match between cache.save and
	// cache.restore.
	PreserveSymlinks bool `mapstructure:"preserve_symlinks"`

	// AwsKey, AwsSecret, and AwsSessionToken are the user's credentials for
	// authenticating interactions with S3.
	AwsKey          string `mapstructure:"aws_key" plugin:"expand"`
	AwsSecret       string `mapstructure:"aws_secret" plugin:"expand"`
	AwsSessionToken string `mapstructure:"aws_session_token" plugin:"expand"`

	// RoleARN is an ARN that should be assumed to make the S3 request.
	RoleARN string `mapstructure:"role_arn" plugin:"expand"`

	// Region is the S3 region where the bucket is located. It defaults to
	// "us-east-1".
	Region string `mapstructure:"region" plugin:"region"`

	// assumedRoleARN is set when the command is using temporary credentials
	// that were generated by an ec2.assume_role command.
	assumedRoleARN string

	// existingCredentials holds passed-in temporary credentials and their
	// expiration, populated by an ec2.assume_role command.
	existingCredentials *aws.Credentials

	bucket   pail.Bucket
	taskData client.TaskData
}

// decodeCacheParams decodes raw command params into the given command struct.
func decodeCacheParams(params map[string]any, result any) error {
	decoder, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		WeaklyTypedInput: true,
		Result:           result,
	})
	if err != nil {
		return errors.Wrap(err, "initializing mapstructure decoder")
	}
	return errors.Wrap(decoder.Decode(params), "decoding mapstructure params")
}

// validateCommon adds the validation errors shared by both cache commands.
func (c *cacheCommon) validateCommon(catcher grip.Catcher) {
	catcher.Add(validateCacheName(c.CacheName))
	catcher.Wrapf(validateS3BucketName(c.Bucket), "validating bucket name '%s'", c.Bucket)
	catcher.NewWhen(c.RemotePath == "", "remote_path cannot be blank")
	catcher.NewWhen(len(c.KeyExpansions) == 0, "at least one key_expansions value is required")
	validateCacheCredentials(catcher, c.RoleARN, c.AwsKey, c.AwsSecret, c.AwsSessionToken)
}

// expandParams applies expansions to the embedding command (so command-specific
// expandable fields are covered too) and defaults the region.
func (c *cacheCommon) expandParams(command any, conf *internal.TaskConfig) error {
	if err := util.ExpandValues(command, &conf.Expansions); err != nil {
		return errors.Wrap(err, "applying expansions")
	}
	if c.Region == "" {
		c.Region = evergreen.DefaultEC2Region
	}
	return nil
}

// populateAssumedRole adopts temporary credentials supplied by an
// ec2.assume_role command, if any are present for this session token.
func (c *cacheCommon) populateAssumedRole(conf *internal.TaskConfig) {
	expiration, found := getAssumedRoleExpiration(conf, c.AwsSessionToken)
	if !found {
		return
	}
	if info := getAssumedRoleInfo(conf, c.AwsSessionToken); info != nil {
		c.assumedRoleARN = info.RoleARN
	}
	c.existingCredentials = &aws.Credentials{
		AccessKeyID:     c.AwsKey,
		SecretAccessKey: c.AwsSecret,
		SessionToken:    c.AwsSessionToken,
		Expires:         expiration,
		CanExpire:       true,
	}
}

// resolveCacheKey computes the cache key from the key files (resolved against
// the working directory) and the key expansions.
func (c *cacheCommon) resolveCacheKey(conf *internal.TaskConfig) (string, error) {
	keyFiles := make([]string, len(c.KeyFiles))
	for i, keyFile := range c.KeyFiles {
		keyFiles[i] = GetWorkingDirectory(conf, keyFile)
	}
	return computeCacheKey(keyFiles, c.KeyExpansions, c.PreserveSymlinks)
}

// remoteKey returns the S3 object key for a cache with the given content key.
// This layout is the contract that lets a cache.save be found by a later
// cache.restore, so it lives in one place.
func (c *cacheCommon) remoteKey(key string) string {
	return path.Join(c.RemotePath, key, c.CacheName+cacheArchiveSuffix)
}

// createTempCacheArchive creates a uniquely named temporary file in workDir for
// the cache tarball and returns its path. The unique name avoids colliding with
// or overwriting a user file in the working directory; the caller is
// responsible for removing it.
func createTempCacheArchive(workDir string) (string, error) {
	f, err := os.CreateTemp(workDir, "cache-*"+cacheArchiveSuffix)
	if err != nil {
		return "", errors.Wrap(err, "creating temporary cache archive file")
	}
	// Close immediately; callers reopen the path via the archive writer or the
	// S3 download. The file must be closed before it can be removed on Windows.
	if err := f.Close(); err != nil {
		return "", errors.Wrapf(err, "closing temporary cache archive file '%s'", f.Name())
	}
	return f.Name(), nil
}

func (c *cacheCommon) getRoleARN() string {
	if c.assumedRoleARN != "" {
		return c.assumedRoleARN
	}
	return c.RoleARN
}

// createPailBucket connects to S3 and stores the bucket on the receiver. Set
// ifNotExists for save semantics, where an existing object must not be
// overwritten.
func (c *cacheCommon) createPailBucket(ctx context.Context, comm client.Communicator, httpClient *http.Client, ifNotExists bool) error {
	opts := pail.S3Options{
		Region:      c.Region,
		Name:        c.Bucket,
		IfNotExists: ifNotExists,
	}
	if c.getRoleARN() != "" {
		opts.Credentials = createEvergreenCredentials(comm, c.taskData, c.existingCredentials, c.getRoleARN(), nil)
	} else if c.AwsKey != "" {
		opts.Credentials = pail.CreateAWSStaticCredentials(c.AwsKey, c.AwsSecret, c.AwsSessionToken)
	}

	bucket, err := pail.NewS3MultiPartBucketWithHTTPClient(ctx, httpClient, opts)
	c.bucket = bucket
	return err
}

// retryS3Op runs op with the same exponential backoff the other S3 commands use
// for transient errors. The op closure returns whether the error is retryable,
// so the caller can mark terminal outcomes (e.g. a cache miss or a benign
// already-exists response) as non-retryable. Each attempt is logged to the task
// logger, matching the other S3 commands.
func retryS3Op(ctx context.Context, logger grip.Journaler, description string, op utility.RetryableFunc) error {
	attempt := 0
	return utility.Retry(ctx, func() (bool, error) {
		attempt++
		logger.Infof(ctx, "Attempting to %s (attempt %d of %d).", description, attempt, maxS3OpAttempts)
		canRetry, err := op()
		if err != nil && canRetry {
			logger.Errorf(ctx, "Problem while attempting to %s, retrying: %s", description, err)
		}
		return canRetry, err
	}, utility.RetryOptions{
		MaxAttempts: maxS3OpAttempts,
		MinDelay:    s3OpSleep,
		MaxDelay:    s3OpRetryMaxSleep,
	})
}

// isS3ClientError reports whether err is an S3 API error caused by a client
// (4xx) fault. Such errors won't succeed on retry, so callers should treat them
// as terminal rather than burning the retry budget.
func isS3ClientError(err error) bool {
	var apiErr smithy.APIError
	return errors.As(err, &apiErr) && apiErr.ErrorFault() == smithy.FaultClient
}

// setCacheHit records whether a cache was hit in the cache-hit expansion that
// cache.restore sets and cache.save reads.
func setCacheHit(conf *internal.TaskConfig, cacheName string, hit bool) {
	value := ""
	if hit {
		value = cacheHitValue
	}
	conf.Expansions.Put(cacheHitExpansionName(cacheName), value)
}

// cacheWasHit reports whether the cache-hit expansion for cacheName is set,
// indicating cache.restore already found a hit this task.
func cacheWasHit(conf *internal.TaskConfig, cacheName string) bool {
	return conf.Expansions.Get(cacheHitExpansionName(cacheName)) == cacheHitValue
}

// validateCacheName checks that name is set and uses only allowed characters.
// Character validation is deferred for expandable values, since the resolved
// name is re-validated after expansions are applied.
func validateCacheName(name string) error {
	if name == "" {
		return errors.New("name cannot be blank")
	}
	if util.IsExpandable(name) {
		return nil
	}
	if !cacheNameRegex.MatchString(name) {
		return errors.Errorf("name '%s' must match %s", name, cacheNameRegex.String())
	}
	return nil
}

// validateCacheCredentials enforces the same credential shape as s3.put: either
// a role ARN, or an AWS key and secret, but not both.
func validateCacheCredentials(catcher grip.Catcher, roleARN, awsKey, awsSecret, awsSessionToken string) {
	if roleARN != "" {
		catcher.NewWhen(awsKey != "", "AWS key must be empty when using role ARN")
		catcher.NewWhen(awsSecret != "", "AWS secret must be empty when using role ARN")
		catcher.NewWhen(awsSessionToken != "", "AWS session token must be empty when using role ARN")
	} else {
		catcher.NewWhen(awsKey == "", "AWS key cannot be blank")
		catcher.NewWhen(awsSecret == "", "AWS secret cannot be blank")
	}
}

// computeCacheKey returns a hex-encoded SHA-256 over the key files followed by
// the expansion values, in the order given. The key is order-sensitive. Each
// section is length-prefixed and each entry is self-delimiting (key files
// contribute a fixed-size per-file digest, expansions are length-prefixed) so
// inputs can't run together: a key file containing "a" plus expansion "b" hashes
// differently from expansions ["a", "b"]. Nothing about the runtime environment
// is folded in implicitly; callers include values like "${distro_id}" through
// keyExpansions if they want that partitioning. The preserveSymlinks flag is
// folded in only when enabled, so symlink-aware caches occupy a distinct key
// space while keys computed before the option existed stay valid. This is
// unambiguous because the encoding is self-delimiting: no flag-less input can
// produce the same byte stream as another input plus the trailing
// discriminator.
func computeCacheKey(keyFiles, keyExpansions []string, preserveSymlinks bool) (string, error) {
	h := sha256.New()
	writeUint64 := func(n int) {
		var buf [8]byte
		binary.BigEndian.PutUint64(buf[:], uint64(n))
		h.Write(buf[:])
	}

	writeUint64(len(keyFiles))
	for _, keyFile := range keyFiles {
		f, err := os.Open(keyFile)
		if err != nil {
			return "", errors.Wrapf(err, "opening key file '%s'", keyFile)
		}
		fileHash := sha256.New()
		_, err = io.Copy(fileHash, f)
		closeErr := f.Close()
		if err != nil {
			return "", errors.Wrapf(err, "hashing key file '%s'", keyFile)
		}
		if closeErr != nil {
			return "", errors.Wrapf(closeErr, "closing key file '%s'", keyFile)
		}
		// A fixed-width per-file digest is self-delimiting, so file contents
		// can't merge with the following entries.
		h.Write(fileHash.Sum(nil))
	}

	writeUint64(len(keyExpansions))
	for _, value := range keyExpansions {
		writeUint64(len(value))
		h.Write([]byte(value))
	}

	if preserveSymlinks {
		h.Write([]byte{1})
	}

	return hex.EncodeToString(h.Sum(nil)), nil
}

// cacheHitExpansionName returns the name of the expansion that cache.restore
// sets and cache.save reads. Dashes in the cache name become underscores so the
// result is a usable shell variable name (e.g. "mise-and-go" -> "mise_and_go_cache_hit").
func cacheHitExpansionName(name string) string {
	return strings.ReplaceAll(name, "-", "_") + "_cache_hit"
}

// makeCacheArchive bundles paths (relative to workDir, or absolute) into a
// gzipped tarball at target. It reuses the same archive helpers as
// archive.targz_pack. A path that does not exist on disk is an error. When
// preserveSymlinks is true, symlinks are archived as symlinks rather than
// dereferenced.
func makeCacheArchive(ctx context.Context, workDir string, paths []string, target string, logger grip.Journaler, preserveSymlinks bool) error {
	contents, totalSize, err := gatherCacheContents(workDir, paths)
	if err != nil {
		return err
	}

	useParallelGzip := totalSize > thresholdSizeForParallelGzipCompression
	f, gz, tarWriter, err := tarGzWriter(target, useParallelGzip)
	if err != nil {
		return errors.Wrapf(err, "creating archive file '%s'", target)
	}
	defer func() {
		logger.Error(ctx, tarWriter.Close())
		logger.Error(ctx, gz.Close())
		logger.Error(ctx, f.Close())
	}()

	_, err = buildArchive(ctx, buildArchiveOptions{
		tarWriter:        tarWriter,
		rootPath:         workDir,
		paths:            contents,
		logger:           logger,
		preserveSymlinks: preserveSymlinks,
	})
	return errors.Wrap(err, "building cache archive")
}

// gatherCacheContents resolves each path to the set of files to archive,
// walking directories recursively. Paths are interpreted relative to workDir
// unless absolute. A missing path is an error so a misconfigured cache.save
// fails loudly rather than uploading an incomplete archive.
func gatherCacheContents(workDir string, paths []string) ([]archiveContentFile, int, error) {
	var contents []archiveContentFile
	totalSize := 0
	for _, p := range paths {
		fullPath := p
		if !filepath.IsAbs(fullPath) {
			fullPath = filepath.Join(workDir, p)
		}

		info, err := os.Lstat(fullPath)
		if err != nil {
			return nil, 0, errors.Wrapf(err, "locating path '%s'", p)
		}

		if !info.IsDir() {
			contents = append(contents, archiveContentFile{path: fullPath, info: info})
			if info.Mode().IsRegular() {
				totalSize += int(info.Size())
			}
			continue
		}

		err = filepath.WalkDir(fullPath, func(walkPath string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			fi, err := d.Info()
			if err != nil {
				return errors.Wrapf(err, "getting file info for '%s'", walkPath)
			}
			contents = append(contents, archiveContentFile{path: walkPath, info: fi})
			if fi.Mode().IsRegular() {
				totalSize += int(fi.Size())
			}
			return nil
		})
		if err != nil {
			return nil, 0, errors.Wrapf(err, "walking directory '%s'", p)
		}
	}

	return contents, totalSize, nil
}
