---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    # Ensure packages have been released for at least 3 days before opening an upgrade PR
    cooldown:
      default-days: 3
    commit-message:
      prefix: "CHORE: "
    ignore:
      # TODO (DEVPROD-35241): Ignore AWS SDK upgrades until the planned bump.
      - dependency-name: "github.com/aws/aws-sdk-go-v2*"
      # TODO (DEVPROD-28491): Ignore upgrades that require Go 1.25.0,
      # which Evergreen cannot use for now (all packages below).
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/99designs/gqlgen"
      - dependency-name: "github.com/bradleyfalzon/ghinstallation/v2"
      - dependency-name: "github.com/parquet-go/parquet-go"
      - dependency-name: "github.com/vektah/gqlparser/v2"
      - dependency-name: "golang.org/x/crypto"
      - dependency-name: "golang.org/x/sync"
      - dependency-name: "golang.org/x/text"
      - dependency-name: "golang.org/x/tools"
    groups:
      otel-dependencies:
        applies-to: version-updates
        patterns:
          - go.opentelemetry.io/*
      aws-dependencies:
        applies-to: version-updates
        patterns:
          - github.com/aws/aws-sdk-go-v2*
