---
linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - structcheck
    - asciicheck
    - unused
    - gosimple
    - deadcode

linters-settings:
  govet:
    check-shadowing: false
