---
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - ineffassign
    - goconst
    - goimports
    - gosimple
    - govet
    - misspell
    - unconvert
    - unused

linters-settings:
  goconst:
    ignore-tests: true
    numbers: true
