---
linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - govet
    - ineffassign
    - interfacer
    - misspell
    - typecheck
    - unconvert

run:
  skip-dirs:
    - build
issues:
  exclude-rules:
    - linters:
      - errcheck
      text: "return value of .* is not checked.*defer"
  # Ignore existing lint problems
  new: true
