---
linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - ineffassign
    - misspell
    - typecheck
      # TODO: custom linter probably needs to go in run-linter.

run:
  skip-dirs:
    - build
issues:
  exclude-rules:
    - linters:
        - goconst
      # Ignore GOOS warnings.
      text: "string `windows`"
    - path: _test\.go
      linters:
        - gocognit
        - goconst
