---
linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - ineffassign
    - goimports
    - gosimple
    - govet
    - misspell
    - unconvert
    - unused

linters-settings:
  testifylint:
    disable:
      - require-error