apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: evergreen
  description: Internal CI System
  tags:
    - ci
  links:
    - url: https://spruce.mongodb.com
      title: Evergreen UI
      icon: dashboard
spec:
  owner: evergreen-app

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: evergreen-backend
  description: Evergreen backend service
  annotations:
    evergreen/project-id: evergreen
  tags:
    - golang
spec:
  type: service
  owner: evergreen-app
  lifecycle: production
  system: evergreen
  domain: internal-tools
  providesApis:
    - evergreen-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: evergreen-api
  description: Retrieve Evergreen Data
spec:
  type: openapi
  lifecycle: production
  owner: evergreen-app
  system: evergreen
  definition:
    $text: https://mciuploads.s3.amazonaws.com/evergreen/latest/swagger.json
