apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: evergreen
  description: Internal CI System
  annotations:
    evergreen/project-id: evergreen
spec:
  type: service
  owner: evergreen-app
  lifecycle: production
