version: "3"
services:
  evergreen:
    entrypoint: /srv/clients/linux_amd64/evergreen service web
    depends_on: 
      - mongo
    ports:
      - 9090:9090
    build:
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://mongo:27017
  mongo:
    build:
      dockerfile: Dockerfile-seeded-mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    ports:
      - 27017
volumes:
  mongo-data:
