package operations

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/mongodb/grip"
	"github.com/pkg/errors"
	"github.com/urfave/cli"
)

func Client() cli.Command {
	return cli.Command{
		Name:  "client",
		Usage: "convenience methods for scripts which use client settings",
		Subcommands: []cli.Command{
			getUser(),
			getAPIKey(),
			getAPIUrl(),
			getUIUrl(),
			getJWTFromKanopy(),
		},
	}
}

// a list of strings that indicate that kanopy-oidc is not installed or not in the PATH.
var kanopyOIDCNotInstalledMessages = []string{
	"executable file not found in $PATH",
	"command not found",
}

const (
	optOutTextIntro = "Evergreen CLI will attempt to retrieve or generate a JWT token. "
	optOutText      = "To opt out of this, set 'do_not_run_kanopy_oidc' to true in your config file. Opting out is only available temporarily until deprecation, please see DEVPROD-4160."
)

// runKanopyOIDCLogin executes the kanopy-oidc login command and captures the JWT token from the output.
// It also displays output to the user in real-time while ensuring that the JWT token is not printed.
func runKanopyOIDCLogin(reason string) (string, error) {
	cmd := exec.Command("kanopy-oidc", "login", "-n", "-f", "device")

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return "", errors.Wrap(err, "creating stdout pipe")
	}

	cmd.Stderr = os.Stderr // Show stderr output directly to the user

	// Start the command
	if err := cmd.Start(); err != nil {
		// if the error is that kanopy-oidc is not installed, link the installation instructions
		for _, msg := range kanopyOIDCNotInstalledMessages {
			if strings.Contains(err.Error(), msg) {
				printKanopyAuthHeader(true)
				grip.Info(
					"The Evergreen CLI would like to use kanopy-oidc to authenticate you, but it is not installed or not in your PATH.\n" +
						"Please follow the installation instructions at: go/install-kanopy-oidc-evergreen\n" +
						"\n" + optOutText,
				)
				printKanopyAuthHeader(false)
				return "", nil
			}
		}
		return "", errors.Wrap(err, "starting kanopy-oidc login")
	}

	// Process the output - display non-token outputs and capture the token
	var tokenBuf bytes.Buffer
	scanner := bufio.NewScanner(stdout)
	var printedURL, printedHeader bool
	for scanner.Scan() {
		line := scanner.Text()

		// Check if the line contains a JWT (usually starts with "ey")
		if len(line) > 30 && strings.HasPrefix(line, "ey") {
			// This is likely the JWT token - capture but don't display
			tokenBuf.WriteString(line)
		} else {
			printedURL = true
			// only print the header once
			if !printedHeader {
				printKanopyAuthHeader(true)
				if reason != "" {
					grip.Info(reason)
				}
				grip.Info(optOutTextIntro + optOutText)
				printedHeader = true
			}
			// This is not a JWT token - display to the user
			grip.Info(line)
		}
	}

	if printedURL {
		printKanopyAuthHeader(false)
	}

	// Wait for command to complete
	if err := cmd.Wait(); err != nil {
		return "", errors.Wrap(err, "waiting for kanopy-oidc login to complete")
	}

	if tokenBuf.Len() == 0 {
		return "", errors.New("no token received - ensure kanopy-oidc is installed and configured correctly")
	}

	return tokenBuf.String(), nil
}

func getUser() cli.Command {
	return cli.Command{
		Name:    "get-user",
		Aliases: []string{"user"},
		Usage:   "get username from client settings",
		Action: func(c *cli.Context) error {
			confPath := c.Parent().String(confFlagName)
			conf, err := NewClientSettings(confPath)
			if err != nil {
				return errors.Wrap(err, "loading configuration")
			}
			fmt.Println(conf.User)
			return nil
		},
	}
}

func getAPIKey() cli.Command {
	return cli.Command{
		Name:    "get-api-key",
		Aliases: []string{"key"},
		Usage:   "get API key from client settings",
		Action: func(c *cli.Context) error {
			confPath := c.Parent().String(confFlagName)
			conf, err := NewClientSettings(confPath)
			if err != nil {
				return errors.Wrap(err, "loading configuration")
			}
			fmt.Println(conf.APIKey)
			return nil
		},
	}
}

func getAPIUrl() cli.Command {
	return cli.Command{
		Name:    "get-api-url",
		Aliases: []string{"api"},
		Usage:   "get API URL from client settings",
		Action: func(c *cli.Context) error {
			confPath := c.Parent().String(confFlagName)
			conf, err := NewClientSettings(confPath)
			if err != nil {
				return errors.Wrap(err, "loading configuration")
			}
			fmt.Println(conf.APIServerHost)
			return nil
		},
	}
}

func getUIUrl() cli.Command {
	return cli.Command{
		Name:    "get-ui-url",
		Aliases: []string{"ui"},
		Usage:   "get UI URL from client settings",
		Action: func(c *cli.Context) error {
			confPath := c.Parent().String(confFlagName)
			conf, err := NewClientSettings(confPath)
			if err != nil {
				return errors.Wrap(err, "loading configuration")
			}
			fmt.Println(conf.UIServerHost)
			return nil
		},
	}
}

func getJWTFromKanopy() cli.Command {
	return cli.Command{
		Name:    "get-jwt",
		Usage:   "get a JWT generated by kanopy-oidc",
		Aliases: []string{"jwt"},
		Action: func(c *cli.Context) error {
			jwt, _ := runKanopyOIDCLogin("")
			fmt.Println(jwt)
			return nil
		},
	}
}
