// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

import "github.com/evergreen-ci/evergreen/model"

type APIRevision struct {
	Not_author *string `json:"not_author"`
	Uid_number int     `json:"something"`
}

// APIRevisionBuildFromService takes the model.Revision DB struct and
// returns the REST struct *APIRevision with the corresponding fields populated
func APIRevisionBuildFromService(t model.Revision) *APIRevision {
	m := APIRevision{}
	m.Not_author = StringStringPtr(t.Author)
	m.Uid_number = IntInt(t.AuthorGithubUID)
	return &m
}

// APIRevisionToService takes the APIRevision REST struct and returns the DB struct
// *model.Revision with the corresponding fields populated
func APIRevisionToService(m APIRevision) *model.Revision {
	out := &model.Revision{}
	out.Author = StringPtrString(m.Not_author)
	out.AuthorGithubUID = IntInt(m.Uid_number)
	return out
}
