// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

func ArrstringArrstringPtr(t []string) []*string {
	m := []*string{}
	for _, e := range t {
		m = append(m, StringStringPtr(e))
	}
	return m
}

func ArrstringPtrArrstring(t []*string) []string {
	m := []string{}
	for _, e := range t {
		m = append(m, StringPtrString(e))
	}
	return m
}

func StringString(in string) string {
	return string(in)
}

func StringStringPtr(in string) *string {
	out := string(in)
	return &out
}

func StringPtrString(in *string) string {
	var out string
	if in == nil {
		return out
	}
	return string(*in)
}

func StringPtrStringPtr(in *string) *string {
	if in == nil {
		return nil
	}
	out := string(*in)
	return &out
}
