// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

import "github.com/evergreen-ci/evergreen/model"

type APIRevision struct {
	Author          *string `json:"author"`
	AuthorGithubUID int     `json:"author_github_u_i_d"`
}

func (m *APIRevision) BuildFromService(t model.Revision) error {
	m.Author = StringStringPtr(t.Author)
	m.AuthorGithubUID = IntInt(t.AuthorGithubUID)
	return nil
}

func (m *APIRevision) ToService() (model.Revision, error) {
	out := model.Revision{}
	out.Author = StringStringPtr(m.Author)
	out.AuthorGithubUID = IntInt(m.AuthorGithubUID)
	return out, nil
}
