// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

import "github.com/evergreen-ci/evergreen/model/user"

type APIGithubUser struct {
	LastKnownAs *string `json:"last_known_as"`
	UID         int     `json:"u_i_d"`
}
type APIUserSettings struct {
	Region     string        `json:"region"`
	GithubUser APIGithubUser `json:"github_user"`
}

func APIGithubUserBuildFromService(t user.GithubUser) *APIGithubUser {
	m := APIGithubUser{}
	m.UID = IntInt(t.UID)
	m.LastKnownAs = StringStringPtr(t.LastKnownAs)
	return &m
}

func APIGithubUserToService(m APIGithubUser) *user.GithubUser {
	out := &user.GithubUser{}
	out.UID = IntInt(m.UID)
	out.LastKnownAs = StringPtrString(m.LastKnownAs)
	return out
}

func APIUserSettingsBuildFromService(t user.UserSettings) *APIUserSettings {
	m := APIUserSettings{}
	m.GithubUser = *APIGithubUserBuildFromService(t.GithubUser)
	m.Region = StringString(t.Region)
	return &m
}

func APIUserSettingsToService(m APIUserSettings) *user.UserSettings {
	out := &user.UserSettings{}
	out.GithubUser = *APIGithubUserToService(m.GithubUser)
	out.Region = StringString(m.Region)
	return out
}
