// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

import "time"

func InterfaceInterface(in interface{}) interface{} {
	return interface{}(in)
}

func InterfaceInterfacePtr(in interface{}) *interface{} {
	out := interface{}(in)
	return &out
}

func InterfacePtrInterface(in *interface{}) interface{} {
	var out interface{}
	if in == nil {
		return out
	}
	return interface{}(*in)
}

func InterfacePtrInterfacePtr(in *interface{}) *interface{} {
	if in == nil {
		return nil
	}
	out := interface{}(*in)
	return &out
}

func MapstringinterfaceMapstringinterface(in map[string]interface{}) map[string]interface{} {
	return map[string]interface{}(in)
}

func MapstringinterfaceMapstringinterfacePtr(in map[string]interface{}) *map[string]interface{} {
	out := map[string]interface{}(in)
	return &out
}

func MapstringinterfacePtrMapstringinterface(in *map[string]interface{}) map[string]interface{} {
	var out map[string]interface{}
	if in == nil {
		return out
	}
	return map[string]interface{}(*in)
}

func MapstringinterfacePtrMapstringinterfacePtr(in *map[string]interface{}) *map[string]interface{} {
	if in == nil {
		return nil
	}
	out := map[string]interface{}(*in)
	return &out
}

func TimeTimeTimeTime(in time.Time) time.Time {
	return time.Time(in)
}

func TimeTimeTimeTimePtr(in time.Time) *time.Time {
	out := time.Time(in)
	return &out
}

func TimeTimePtrTimeTime(in *time.Time) time.Time {
	var out time.Time
	if in == nil {
		return out
	}
	return time.Time(*in)
}

func TimeTimePtrTimeTimePtr(in *time.Time) *time.Time {
	if in == nil {
		return nil
	}
	out := time.Time(*in)
	return &out
}
