// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

import "time"

func InterfaceInterface(in interface{}) interface{} {
	return in
}

func InterfaceInterfacePtr(in interface{}) *interface{} {
	return &in
}

func InterfacePtrInterface(in *interface{}) interface{} {
	var out interface{}
	if in == nil {
		return out
	}
	return *in
}

func InterfacePtrInterfacePtr(in *interface{}) *interface{} {
	return in
}

func MapstringinterfaceMapstringinterface(in map[string]interface{}) map[string]interface{} {
	return in
}

func MapstringinterfaceMapstringinterfacePtr(in map[string]interface{}) *map[string]interface{} {
	return &in
}

func MapstringinterfacePtrMapstringinterface(in *map[string]interface{}) map[string]interface{} {
	var out map[string]interface{}
	if in == nil {
		return out
	}
	return *in
}

func MapstringinterfacePtrMapstringinterfacePtr(in *map[string]interface{}) *map[string]interface{} {
	return in
}

func TimeTimeTimeTime(in time.Time) time.Time {
	return in
}

func TimeTimeTimeTimePtr(in time.Time) *time.Time {
	return &in
}

func TimeTimePtrTimeTime(in *time.Time) time.Time {
	var out time.Time
	if in == nil {
		return out
	}
	return *in
}

func TimeTimePtrTimeTimePtr(in *time.Time) *time.Time {
	return in
}
