// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

import "github.com/vektah/gqlparser/ast"

type APISource struct {
	Name  string `json:"name"`
	Input string `json:"input"`
}

func (m *APISource) BuildFromService(t ast.Source) error {
	m.Input = StringString(t.Input)
	m.Name = StringString(t.Name)
	return nil
}

func (m *APISource) ToService() (ast.Source, error) {
	out := ast.Source{}
	out.Input = StringString(m.Input)
	out.Name = StringString(m.Name)
	return out, nil
}
