// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

func StringString(in string) string {
	return in
}

func StringStringPtr(in string) *string {
	return &in
}

func StringPtrString(in *string) string {
	var out string
	if in == nil {
		return out
	}
	return *in
}

func StringPtrStringPtr(in *string) *string {
	return in
}
