// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

import "github.com/evergreen-ci/evergreen/rest/model"

type APIMockTypes struct {
	BoolType       bool     `json:"bool_type"`
	BoolPtrType    *bool    `json:"bool_ptr_type"`
	IntType        int      `json:"int_type"`
	IntPtrType     *int     `json:"int_ptr_type"`
	StringType     string   `json:"string_type"`
	StringPtrType  *string  `json:"string_ptr_type"`
	Uint64Type     int      `json:"uint64_type"`
	Uint64PtrType  *int     `json:"uint64_ptr_type"`
	Float64Type    float64  `json:"float64_type"`
	Float64PtrType *float64 `json:"float64_ptr_type"`
	RuneType       int      `json:"rune_type"`
	RunePtrType    *int     `json:"rune_ptr_type"`
}

func APIMockTypesBuildFromService(t model.MockTypes) *APIMockTypes {
	m := APIMockTypes{}
	m.BoolPtrType = BoolPtrBoolPtr(t.BoolPtrType)
	m.BoolType = BoolBool(t.BoolType)
	m.Float64PtrType = Float64PtrFloat64Ptr(t.Float64PtrType)
	m.Float64Type = Float64Float64(t.Float64Type)
	m.IntPtrType = IntPtrIntPtr(t.IntPtrType)
	m.IntType = IntInt(t.IntType)
	m.RunePtrType = RunePtrIntPtr(t.RunePtrType)
	m.RuneType = RuneInt(t.RuneType)
	m.StringPtrType = StringPtrStringPtr(t.StringPtrType)
	m.StringType = StringString(t.StringType)
	m.Uint64PtrType = Uint64PtrIntPtr(t.Uint64PtrType)
	m.Uint64Type = Uint64Int(t.Uint64Type)
	return &m
}

func APIMockTypesToService(m APIMockTypes) *model.MockTypes {
	out := &model.MockTypes{}
	out.BoolPtrType = BoolPtrBoolPtr(m.BoolPtrType)
	out.BoolType = BoolBool(m.BoolType)
	out.Float64PtrType = Float64PtrFloat64Ptr(m.Float64PtrType)
	out.Float64Type = Float64Float64(m.Float64Type)
	out.IntPtrType = IntPtrIntPtr(m.IntPtrType)
	out.IntType = IntInt(m.IntType)
	out.RunePtrType = IntPtrRunePtr(m.RunePtrType)
	out.RuneType = IntRune(m.RuneType)
	out.StringPtrType = StringPtrStringPtr(m.StringPtrType)
	out.StringType = StringString(m.StringType)
	out.Uint64PtrType = IntPtrUint64Ptr(m.Uint64PtrType)
	out.Uint64Type = IntUint64(m.Uint64Type)
	return out
}
