package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/evergreen-ci/evergreen/rest/model"
)

// Port is the resolver for the port field.
func (r *containerPoolResolver) Port(ctx context.Context, obj *model.APIContainerPool) (int, error) {
	return int(obj.Port), nil
}

// Keys is the resolver for the keys field.
func (r *spruceConfigResolver) Keys(ctx context.Context, obj *model.APIAdminSettings) ([]*SSHKey, error) {
	sshKeys := []*SSHKey{}
	for name, location := range obj.Keys {
		sshKeys = append(sshKeys, &SSHKey{
			Location: location,
			Name:     name,
		})
	}
	return sshKeys, nil
}

// ContainerPool returns ContainerPoolResolver implementation.
func (r *Resolver) ContainerPool() ContainerPoolResolver { return &containerPoolResolver{r} }

// SpruceConfig returns SpruceConfigResolver implementation.
func (r *Resolver) SpruceConfig() SpruceConfigResolver { return &spruceConfigResolver{r} }

type containerPoolResolver struct{ *Resolver }
type spruceConfigResolver struct{ *Resolver }
