// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type StatusDetails struct {
	Status string `json:"status"`
	Type   string `json:"type"`
	Desc   string `json:"desc"`
}

type VariantTask struct {
	DisplayName string    `json:"display_name"`
	Tasks       []*string `json:"tasks"`
}
