// Code generated by graphql/redact_secrets_plugin.go DO NOT EDIT.
package graphql

var redactedFields = map[string]bool{
	"publicKey": true,
	"secret": true,
	"servicePassword": true,
	"vars": true,
}
