// Code generated by graphql/redact_secrets_plugin.go DO NOT EDIT.
package graphql

var redactedFields = map[string]bool{
	"appId": true,
	"clientId": true,
	"clientSecret": true,
	"defaultOwner": true,
	"defaultRepo": true,
	"github": true,
	"amboyDB": true,
	"csrfKey": true,
	"githubAppAuth": true,
	"headerName": true,
	"issuer": true,
	"kanopy": true,
	"keysetURL": true,
	"multi": true,
	"naive": true,
	"okta": true,
	"organization": true,
	"preferredType": true,
	"publicKey": true,
	"secret": true,
	"senderAddress": true,
	"servicePassword": true,
	"vars": true,
}
