package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/evergreen-ci/evergreen/validator"
)

// Level is the resolver for the level field.
func (r *validationErrorResolver) Level(ctx context.Context, obj *validator.ValidationError) (int, error) {
	return int(obj.Level), nil
}

// ValidationError returns ValidationErrorResolver implementation.
func (r *Resolver) ValidationError() ValidationErrorResolver { return &validationErrorResolver{r} }

type validationErrorResolver struct{ *Resolver }
