database:
  url: "mongodb://localhost:27017"
  db: "mci"
  write_concern:
    wmode: majority

configdir: "config_test"
client_binaries_dir: "clients"
credentials: {
  github: "github_token",
}

api_url: http://localhost:8080
api:
  github_webhook_secret: "test"
  httplistenaddr: ":8080"
ui:
  secret: "secret for UI"
  defaultproject: "logkeeper"
  url: "http://localhost:9090"
  httplistenaddr: ":9090"

notify:
  logfile: "evg_notify.log"
  smtp:
    from: "notifications@example.com"
    server: "localhost"
    port: 25
    admin_email:
      - "admin@example.com"

runner:
    intervalseconds: 10

auth:
    naive:
        users:
        - username: "admin"
          password: "password"
          display_name: "Evergreen Admin"

plugins:
  buildbaron:
          host: "jira.example.com"
          username: "foo"
          password: "bar"
          projects:
                  "logkeeper":
                          ticket_create_project: "foo"
                          ticket_search_projects: ["foo"]
