// Code generated by rest/model/codegen.go. DO NOT EDIT.

package model

import "github.com/evergreen-ci/evergreen/model"

type APIRevision struct {
	Author          *string `json:"author"`
	AuthorGithubUID int     `json:"author_github_u_i_d"`
}

// APIRevisionBuildFromService takes the model.Revision DB struct and
// returns the REST struct *APIRevision with the corresponding fields populated
func APIRevisionBuildFromService(t model.Revision) *APIRevision {
	m := APIRevision{}
	m.Author = StringStringPtr(t.Author)
	m.AuthorGithubUID = IntInt(t.AuthorGithubUID)
	return &m
}

// APIRevisionToService takes the APIRevision REST struct and returns the DB struct
// *model.Revision with the corresponding fields populated
func APIRevisionToService(m APIRevision) *model.Revision {
	out := &model.Revision{}
	out.Author = StringPtrString(m.Author)
	out.AuthorGithubUID = IntInt(m.AuthorGithubUID)
	return out
}
