// Code generated by legacy codegen tool.
// Manual edits are allowed but please do not replicate this code style.

package model

import (
	"github.com/evergreen-ci/evergreen/model/commitqueue"
	"github.com/evergreen-ci/evergreen/model/patch"
	"github.com/evergreen-ci/evergreen/model/task"
	"github.com/evergreen-ci/evergreen/model/user"
)

type APIBaseTaskInfo struct {
	Id     *string `json:"id"`
	Status *string `json:"status"`
}
type APIDisplayTask struct {
	Name           *string  `json:"name"`
	ExecutionTasks []string `json:"execution_tasks"`
}
type APIModule struct {
	Module *string `json:"module"`
	Issue  *string `json:"issue"`
}
type APIDBUser struct {
	UserID       *string  `json:"user_id"`
	DisplayName  *string  `json:"display_name"`
	OnlyApi      bool     `json:"only_api"`
	Roles        []string `json:"roles"`
	EmailAddress *string  `json:"email_address"`
}

// APIBaseTaskInfoBuildFromService takes the task.BaseTaskInfo DB struct and
// returns the REST struct *APIBaseTaskInfo with the corresponding fields populated
func APIBaseTaskInfoBuildFromService(t task.BaseTaskInfo) *APIBaseTaskInfo {
	m := APIBaseTaskInfo{}
	m.Id = StringStringPtr(t.Id)
	m.Status = StringStringPtr(t.Status)
	return &m
}

// APIBaseTaskInfoToService takes the APIBaseTaskInfo REST struct and returns the DB struct
// *task.BaseTaskInfo with the corresponding fields populated
func APIBaseTaskInfoToService(m APIBaseTaskInfo) *task.BaseTaskInfo {
	out := &task.BaseTaskInfo{}
	out.Id = StringPtrString(m.Id)
	out.Status = StringPtrString(m.Status)
	return out
}

// APIDisplayTaskBuildFromService takes the patch.DisplayTask DB struct and
// returns the REST struct *APIDisplayTask with the corresponding fields populated
func APIDisplayTaskBuildFromService(t patch.DisplayTask) *APIDisplayTask {
	m := APIDisplayTask{}
	m.ExecutionTasks = ArrstringArrstring(t.ExecTasks)
	m.Name = StringStringPtr(t.Name)
	return &m
}

// APIDisplayTaskToService takes the APIDisplayTask REST struct and returns the DB struct
// *patch.DisplayTask with the corresponding fields populated
func APIDisplayTaskToService(m APIDisplayTask) *patch.DisplayTask {
	out := &patch.DisplayTask{}
	out.ExecTasks = ArrstringArrstring(m.ExecutionTasks)
	out.Name = StringPtrString(m.Name)
	return out
}

// APIModuleBuildFromService takes the commitqueue.Module DB struct and
// returns the REST struct *APIModule with the corresponding fields populated
func APIModuleBuildFromService(t commitqueue.Module) *APIModule {
	m := APIModule{}
	m.Module = StringStringPtr(t.Module)
	m.Issue = StringStringPtr(t.Issue)
	return &m
}

// APIModuleToService takes the APIModule REST struct and returns the DB struct
// *commitqueue.Module with the corresponding fields populated
func APIModuleToService(m APIModule) *commitqueue.Module {
	out := &commitqueue.Module{}
	out.Module = StringPtrString(m.Module)
	out.Issue = StringPtrString(m.Issue)
	return out
}

// APIDBUserBuildFromService takes the user.DBUser DB struct and
// returns the REST struct *APIDBUser with the corresponding fields populated
func APIDBUserBuildFromService(t user.DBUser) *APIDBUser {
	m := APIDBUser{}
	m.DisplayName = StringStringPtr(t.DispName)
	m.Roles = ArrstringArrstring(t.SystemRoles)
	m.UserID = StringStringPtr(t.Id)
	m.OnlyApi = BoolBool(t.OnlyAPI)
	return &m
}

// APIDBUserToService takes the APIDBUser REST struct and returns the DB struct
// *user.DBUser with the corresponding fields populated
func APIDBUserToService(m APIDBUser) *user.DBUser {
	out := &user.DBUser{}
	out.DispName = StringPtrString(m.DisplayName)
	out.Id = StringPtrString(m.UserID)
	out.SystemRoles = ArrstringArrstring(m.Roles)
	out.OnlyAPI = BoolBool(m.OnlyApi)
	return out
}
